/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitesWebRouteImport } from './routes/sites-web'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OutilsMetierRouteImport } from './routes/outils-metier'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartesNfcRouteImport } from './routes/cartes-nfc'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminNfcRouteImport } from './routes/admin.nfc'
import { Route as ACodeRouteImport } from './routes/a.$code'
import { Route as ApiPlacesSearchRouteImport } from './routes/api/places/search'

const SitesWebRoute = SitesWebRouteImport.update({
  id: '/sites-web',
  path: '/sites-web',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsMetierRoute = OutilsMetierRouteImport.update({
  id: '/outils-metier',
  path: '/outils-metier',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartesNfcRoute = CartesNfcRouteImport.update({
  id: '/cartes-nfc',
  path: '/cartes-nfc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNfcRoute = AdminNfcRouteImport.update({
  id: '/admin/nfc',
  path: '/admin/nfc',
  getParentRoute: () => rootRouteImport,
} as any)
const ACodeRoute = ACodeRouteImport.update({
  id: '/a/$code',
  path: '/a/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesSearchRoute = ApiPlacesSearchRouteImport.update({
  id: '/api/places/search',
  path: '/api/places/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cartes-nfc': typeof CartesNfcRoute
  '/contact': typeof ContactRoute
  '/outils-metier': typeof OutilsMetierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sites-web': typeof SitesWebRoute
  '/a/$code': typeof ACodeRoute
  '/admin/nfc': typeof AdminNfcRoute
  '/api/places/search': typeof ApiPlacesSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cartes-nfc': typeof CartesNfcRoute
  '/contact': typeof ContactRoute
  '/outils-metier': typeof OutilsMetierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sites-web': typeof SitesWebRoute
  '/a/$code': typeof ACodeRoute
  '/admin/nfc': typeof AdminNfcRoute
  '/api/places/search': typeof ApiPlacesSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cartes-nfc': typeof CartesNfcRoute
  '/contact': typeof ContactRoute
  '/outils-metier': typeof OutilsMetierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sites-web': typeof SitesWebRoute
  '/a/$code': typeof ACodeRoute
  '/admin/nfc': typeof AdminNfcRoute
  '/api/places/search': typeof ApiPlacesSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cartes-nfc'
    | '/contact'
    | '/outils-metier'
    | '/sitemap.xml'
    | '/sites-web'
    | '/a/$code'
    | '/admin/nfc'
    | '/api/places/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cartes-nfc'
    | '/contact'
    | '/outils-metier'
    | '/sitemap.xml'
    | '/sites-web'
    | '/a/$code'
    | '/admin/nfc'
    | '/api/places/search'
  id:
    | '__root__'
    | '/'
    | '/cartes-nfc'
    | '/contact'
    | '/outils-metier'
    | '/sitemap.xml'
    | '/sites-web'
    | '/a/$code'
    | '/admin/nfc'
    | '/api/places/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartesNfcRoute: typeof CartesNfcRoute
  ContactRoute: typeof ContactRoute
  OutilsMetierRoute: typeof OutilsMetierRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SitesWebRoute: typeof SitesWebRoute
  ACodeRoute: typeof ACodeRoute
  AdminNfcRoute: typeof AdminNfcRoute
  ApiPlacesSearchRoute: typeof ApiPlacesSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sites-web': {
      id: '/sites-web'
      path: '/sites-web'
      fullPath: '/sites-web'
      preLoaderRoute: typeof SitesWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils-metier': {
      id: '/outils-metier'
      path: '/outils-metier'
      fullPath: '/outils-metier'
      preLoaderRoute: typeof OutilsMetierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartes-nfc': {
      id: '/cartes-nfc'
      path: '/cartes-nfc'
      fullPath: '/cartes-nfc'
      preLoaderRoute: typeof CartesNfcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/nfc': {
      id: '/admin/nfc'
      path: '/admin/nfc'
      fullPath: '/admin/nfc'
      preLoaderRoute: typeof AdminNfcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$code': {
      id: '/a/$code'
      path: '/a/$code'
      fullPath: '/a/$code'
      preLoaderRoute: typeof ACodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places/search': {
      id: '/api/places/search'
      path: '/api/places/search'
      fullPath: '/api/places/search'
      preLoaderRoute: typeof ApiPlacesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartesNfcRoute: CartesNfcRoute,
  ContactRoute: ContactRoute,
  OutilsMetierRoute: OutilsMetierRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SitesWebRoute: SitesWebRoute,
  ACodeRoute: ACodeRoute,
  AdminNfcRoute: AdminNfcRoute,
  ApiPlacesSearchRoute: ApiPlacesSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
